name: flood_edge
channels:
  - conda-forge
  - defaults
dependencies:
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - coloredlogs=15.0.1
  - cuda-cudart=12.9.79
  - cuda-cudart_win-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - h2=4.3.0
  - hpack=4.1.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.4.1.4
  - libcurand=10.3.10.19
  - libcusparse=12.5.10.65
  - libexpat=2.7.3
  - libffi=3.5.2
  - libhwloc=2.12.2
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnvjitlink=12.9.86
  - libsqlite=3.51.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - mkl=2025.3.0
  - mpmath=1.3.0
  - numpy=2.4.2
  - onnxruntime=1.22.2
  - openssl=3.6.1
  - packaging=26.0
  - pip=26.0
  - protobuf=6.33.5
  - pyreadline3=3.5.4
  - pysocks=1.7.1
  - python=3.11.14
  - python-dotenv=1.2.1
  - python-flatbuffers=25.9.23
  - python_abi=3.11
  - pyyaml=6.0.3
  - requests=2.32.5
  - setuptools=80.10.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - urllib3=2.6.3
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.46.3
  - win_inet_pton=1.1.0
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - git-filter-repo==2.47.0
      - opencv-python-headless==4.13.0.90
prefix: C:\Users\Daning\.conda\envs\flood_edge
